### ISSUE TITLE
Error loading swagger UI when flask restplus app deployed to nginx web server

### ISSUE THREAD

**Issue by sanfx** [noirbizarre/flask-restplus#567] opened 2018-12-27 05:11 UTC
I wrote REST API gateway using flask-restplus plugin, I tested it locally it work and even the swagger documentation loads normally but when I try to run the website on server

it works opens in the browser but swagger documentation doesnt shows up in browser console I can see the below error: 

![Image of Yaktocat](https://i.stack.imgur.com/HEvLp.png)

Here is my site nginx configuration: sites-available $ vi clinic_backend

```
server {
        listen 80 default_server;
        listen [::]:80;

        root /var/www/html;

        server_name example.com;

        location /static {
            alias /var/www/html/static/;
        }

        location / {
            try_files $uri @wsgi;
        }

        location @wsgi {
            proxy_pass http://unix:/tmp/gunicorn.sock;
            include proxy_params;
        }

        location ~* .(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
            access_log off;
            log_not_found off;
            expires max;
        }
}
```

**Comment by ziirish** [comment] 2019-03-27 09:33
Hi,

I think this is a duplicate of #223

**Comment by ziirish** [comment] 2019-03-27 09:34
I'm now closing this issue.
Please follow discussions in #223

**Closed by ziirish** 2019-03-27 09:34 UTC
Labels: documentation, duplicate
