### ISSUE TITLE
app.test_client() results is not JSON serializable in 0.8.1

### ISSUE THREAD

**Issue by gddk** [noirbizarre/flask-restplus#102] opened 2015-11-30 19:37 UTC
Upgraded to 0.8.1 and unittests are now producing error:

TypeError: <MagicMock name='mock.validate_payload()()' id='139794117372168'> is not JSON serializable.

When I downgrade to 0.8.0, the problem goes away.

Example erring test:
```
from unittest import TestCase
import json
from vhfs.vm.api.app import app, db


class VmViewPhase2Tests(TestCase):

    def setUp(self):
        db.create_all()
        self.app = app.test_client()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_get_vms(self):
        resp = self.app.get('/api/v1/vms/')
        self.assertEqual(resp.status_code, 200)
        data = json.loads(resp.data.decode('utf-8'))
        self.assertEqual(data, {'results': []})
```

Here's the stack trace:
```
======================================================================
ERROR: test_get_vms (test_vm_phase2.VmViewPhase2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/source/hfs/vhfs/vm/api/web/test/test_vm_phase2.py", line 19, in test_get_vms
    resp = self.app.get('/api/v1/vms/')
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 475, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 504, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/representations/json.py", line 20, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/opt/python35/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MagicMock name='mock.validate_payload()()' id='139794117372168'> is not JSON serializable
```

**Comment by noirbizarre** [comment] 2015-11-30 23:18
Hum, reading your stacktrace, the problem does not comes from flask-restplus (it does not go once in flask-restplus code) but from your mock, which is not serializable (nothing unusual, Mock is not serializable) .

My guess, you mocked an internal behavior which change in 0.8.1, I'll go for this one #81.

**Comment by gddk** [comment] 2015-12-01 16:19
I've realized this bug only occurs when a test with a patch runs before a test that uses test_client.

I've setup a simple example to demonstrate:

```
$ cat test_a.py
from unittest import TestCase
from unittest.mock import patch, MagicMock
from vhfs.vm.api.web.vm import VmView


class VmViewaTests(TestCase):

    @patch('vhfs.vm.api.web.vm.Vm')
    def test_get_calls_filter_by(self, Vm):
        vmId = MagicMock()
        VmView(MagicMock()).get(vmId)
        Vm.query.filter_by.assert_called_once_with(vmId=vmId)
```

```
$ cat test_b.py
from unittest import TestCase
import json
from vhfs.vm.api.app import app, db


class VmViewPhase2Tests(TestCase):

    def setUp(self):
        db.create_all()
        self.app = app.test_client()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_get_vms(self):
        resp = self.app.get('/api/v1/vms/')
        self.assertEqual(resp.status_code, 200)
        data = json.loads(resp.data.decode('utf-8'))
        self.assertEqual(data, {'results': []})
```

```
$ nosetests -v test_a.py
test_get_calls_filter_by (hfs.vhfs.vm.api.test_a.VmViewaTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
```

```
$ nosetests -v test_b.py
test_get_vms (hfs.vhfs.vm.api.test_b.VmViewPhase2Tests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.052s

OK
```


Run them together:
```
$ nosetests -v test_a.py test_b.py
test_get_calls_filter_by (hfs.vhfs.vm.api.test_a.VmViewaTests) ... ok
test_get_vms (hfs.vhfs.vm.api.test_b.VmViewPhase2Tests) ... --------------------------------------------------------------------------------
ERROR in app [/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py:1423]:
Exception on /api/v1/vms/ [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 475, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 504, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/representations/json.py", line 20, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/opt/python35/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MagicMock name='mock.validate_payload()()' id='140695409071552'> is not JSON serializable
FAIL

======================================================================
FAIL: test_get_vms (hfs.vhfs.vm.api.test_b.VmViewPhase2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/source/hfs/vhfs/vm/api/test_b.py", line 18, in test_get_vms
    self.assertEqual(resp.status_code, 200)
AssertionError: 500 != 200
-------------------- >> begin captured logging << --------------------
vhfs.vm.api.app: ERROR: Exception on /api/v1/vms/ [GET]
Traceback (most recent call last):
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 475, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/__init__.py", line 504, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/vagrant/source/hfs/vhfs/vm/api/.venv-vhfs-vm-api/lib/python3.5/site-packages/flask_restful/representations/json.py", line 20, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/opt/python35/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/opt/python35/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MagicMock name='mock.validate_payload()()' id='140695409071552'> is not JSON serializable
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 0.057s

FAILED (failures=1)
```

This problem goes away if I downgrade to v0.8.0.

I suspect there is some caching of something that got introduced in v0.8.1 that is caching the MagicMock() that I passed in test_a.py that is still in memory when I run test_b.py

**Comment by noirbizarre** [comment] 2015-12-01 22:01
This is not flask-restful related (there is not even a line about flask-restplus in the example or the stacktrace) but specific to the way you mock, which seems to rely on on internals which are subject to change between 2 releases

I can't help you on this without a full exemple because:
- I don't know what is `VmView`, what's its implemantation or its behavior
- I don't know what is `vhfs.vm.api.web.vm.Vm`, its implemantation or its behavior
- I don't know why you're mocking vmId
- ...

To summarize, without any real example, I can't help you because your issue is specific to your implementation and the expected behavior and there is no way I can guess what's the problem.

Hint: I think your implementation is simply returning `Vm.query.filter_by(vmId)` which is not serializable.
If this is the case, you can prevent the error by writing:
```python
class VmViewaTests(TestCase):

    @patch('vhfs.vm.api.web.vm.Vm')
    def test_get_calls_filter_by(self, Vm):
        Vm.query.filter_by.return_value = {}  # or whatever you expect as return value
        vmId = 'my_id'
        VmView(MagicMock()).get(vmId)
        Vm.query.filter_by.assert_called_once_with(vmId=vmId)
```

**Comment by noirbizarre** [comment] 2015-12-10 16:47
Hi !

Did you find the solution to your problem ?
Can I close this issue ?

**Comment by gddk** [comment] 2015-12-11 05:01
found a workaround- run two separate nosetests and combine coverage.




On Dec 10, 2015, at 9:47 AM, Axel Haustant <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi !

Did you find the solution to your problem ?
Can I close this issue ?

-

**Closed** 2015-12-11 09:21 UTC
