### ISSUE TITLE
wrong swagger.json path

### ISSUE THREAD

**Issue by dengqianyi** [noirbizarre/flask-restplus#523] opened 2018-09-13 14:44 UTC
http://dev.py.haizb.cn/gifts/1/   
this is my develop test server,and my code and document in there.
you can see , can't get the swagger.json, because the absolute path is http://127.0.0.1:10000/gifts/1/swagger.json.

and i use nginx to proxy uwsgi
nginx.conf like this:

> location / {
                proxy_pass http://127.0.0.1:10000/;
                client_max_body_size 1024m;
                proxy_connect_timeout 1000;
                proxy_set_header X-Real-IP $remote_addr;
}

uwsig.xml like this:

> <uwsgi>
    <pythonpath>/var/www/python</pythonpath>
    <uid>1000</uid>
    <pidfile>/log/python/hzb.pid</pidfile>
    <module>runproduct_debug</module>
    <callable>app</callable>
    <http>127.0.0.1:10000</http>
    <py-autoreload>1</py-autoreload>
    <uwsgi_read_timeout>180</uwsgi_read_timeout>
    <master/>
    <processes>4</processes>
    <memory-report/>
</uwsgi>

i want to know that how to change "http://127.0.0.1:10000/gifts/1/swagger.json"  to "http://dev.py.haizb.cn/gifts/1/swagger.json"

**Comment by dengqianyi** [comment] 2018-09-13 14:52
http://dev.py.haizb.cn/gifts/1/   this is my develop test server.
you can see , can't get the swagger.json, because the absolute path is http://127.0.0.1:10000/gifts/1/swagger.json.

and i use nginx to proxy uwsgi
nginx.conf like this:
location / {
                proxy_pass http://127.0.0.1:10000/;
                client_max_body_size 1024m;
                proxy_connect_timeout 1000;
                proxy_set_header X-Real-IP $remote_addr;
        }

uwsig.xml like this:
<uwsgi>
    <pythonpath>/var/www/python</pythonpath>
    <uid>1000</uid>
    <pidfile>/log/python/hzb.pid</pidfile>
    <module>runproduct_debug</module>
    <callable>app</callable>
    <http>127.0.0.1:10000</http>
    <py-autoreload>1</py-autoreload>
    <uwsgi_read_timeout>180</uwsgi_read_timeout>
    <master/>
    <processes>4</processes>
    <memory-report/>
</uwsgi>

i want to know that how to change "http://127.0.0.1:10000/gifts/1/swagger.json"  to "http://http://dev.py.haizb.cn/gifts/1/swagger.json"

**Comment by dengqianyi** [comment] 2018-09-13 15:03
if i use nginx.conf like this:

> location / {
                include uwsgi_params;
                uwsgi_pass 127.0.0.1:10000;
                #proxy_pass http://127.0.0.1:10000/;
                client_max_body_size 1024m;
                proxy_connect_timeout 1000;
                proxy_set_header X-Real-IP $remote_addr;
        }

uwsgi.xml like this:

> <pythonpath>/var/www/python</pythonpath>
    <uid>1000</uid>
    <pidfile>/log/python/hzb.pid</pidfile>
    <module>rundebug</module>
    <callable>app</callable>
    <socket>127.0.0.1:10000</socket>
    <py-autoreload>1</py-autoreload>
    <uwsgi_read_timeout>180</uwsgi_read_timeout>
    <master/>
    <processes>4</processes>
    <memory-report/>

it will be all right.

who can't help me to right this?

**Comment by ziirish** [comment] 2019-03-26 21:12
Hi,

I think this is a duplicate of #223

**Comment by ziirish** [comment] 2019-03-27 09:34
I'm now closing this issue.
Please follow discussions in #223

**Closed by ziirish** 2019-03-27 09:34 UTC
Labels: documentation, duplicate
